### ISSUE TITLE
Stabilise the SQLite data format written by the CLI

### ISSUE THREAD

**Issue by hellais** [ooni/probe-cli#14]
The model we follow in the probe-cli (and desktop app) is that the tests are run by `probe-cli` and the results are written to two SQLite database tables called `results` and `measurements`.

We make the assumption that the database will only ever be written by `probe-cli`, while `probe-desktop` is only a reader of the sqlite db.

Since this does lead to some pretty tight coupling between the two apps, it's important that we minimise the amount of changes we make to the database schema, since this is kind of a shared model between the two apps.

@lorenzoPrimi and @xanscale brought up a very important issue with the current database model that I think should be addressed sooner than later.

Below is a simplified schema of the current DB:
![screen shot 2018-08-01 at 11 56 46](https://user-images.githubusercontent.com/424620/43515124-0c48c3f4-9582-11e8-978b-182cdae5fb0f.png)

Basically each Results row will have associated to it several Measurement rows. The main issue that @lorenzoPrimi and @xanscal highlighted is the misuse of the column `summary`.

`summary` is an opaque JSON column, which contains in the case of the `Results` table top level information that is to be used for creating the `Results` view (which are relevant to several measurements, ex. the number of tested websites and the number of blocked sites) and we have similar information in each of the `Measurement` summary columns.

The problem is that the `summary` in the `Results` view actually contains values that are computed based on the values of the `Measurements` table. As such it's tricky to keep these two columns in sync and we are actually duplicating some information that could otherwise be computed with a query.

The reason to follow this approach initially, was that, in particular for the sums, we didn't want to have to scan through all the rows and parse JSON from `summary` for every row (SQLite JSON support is a bit iffy: https://www.sqlite.org/json1.html). However by doing some refactoring of this table and for the counts putting everything in a dedicated `anomaly` column, we can maybe get around this.

It would be great if we were to come up with a schema that we think can work for both mobile and desktop apps and share an approach for doing this so we don't have to re-invent the wheel.

I believe this is a requirement to having a beta release as changes in this area will impact several bits of the desktop app.

**Comment by xanscale** [comment]
i think we need to follow this criterias:
1) no data duplication to avoid inconsistance problems
2) head data can be generalized for all test must be outside of summary column

using this criterias i think that summary column in result can be removed and summary column in measurements can contains only test_keys

**Comment by hellais** [comment]
So I believe I have come up with a reasonable model for this.

Here is the proposed schema, with some comments explaining some of the choices: https://gist.github.com/hellais/8308cca261023cb0fb68f46a90094e2a.

@xanscale does this look reasonable to you?

@darkk it would be good to answer the question on the `measurement_id` format.

**Comment by lorenzoPrimi** [comment]
1) Why do you remove ip asn and network name from the Result table? What am I supposed to show in the asn label for the rows in Test result screen?
Getting them from a random Measurement object inside that Result is not an answer
Wouldn't be better to save these data in Result and remove them from Measurement?

2) Why did you remove the measurementState enum? a test can't be done and failed at the same time.

3) If you save input you should add category as well

4) You forgot log_file in Result

5) You forgot `viewed` in the v table, to flag with yellow the non viewed results

**Comment by hellais** [comment]
@lorenzoPrimi thanks for your input!

> 1. 
See this docstring: https://gist.github.com/hellais/8308cca261023cb0fb68f46a90094e2a#file-probe-cli-schema-sql-L32

> 2. Why did you remove the measurementState enum? a test can't be done and failed at the same time.

`done` indicates if it's in the final state. If it is `failed`, then it MUST also be `done`.

> 3. If you save input you should add category as well

I think that for this you ought to rather have a separate table, otherwise you are duplicating the category for every input (and if an input changes category, it will not reflect).

> 4. You forgot log_file in Result

Good call. I don't actually have this on the desktop app, but it's perhaps useful to have.

> 5. You forgot viewed in the v table, to flag with yellow the non viewed results

This I also didn't have in the desktop app. This I guess should also be on the `results` table

**Comment by lorenzoPrimi** [comment]
1) I wanted to avoid to do a subselect on Measurement in the TestResult screen but I guess now it's inevitable
2) All the current algorithms have to change, now can't be done and failed at the same time.
3) I don't understand how you want to implement as the test input list are not stored in the app but will be provided by mk
5) Only a Results can be viewed or not, we don't have the yellow color on Measurement entries

**Comment by xanscale** [comment]
1) the structure is exactly what I thought
2) about specific data left i don't know :)
3) about state i think in different about each of you. i think to distinguish the temporal state from the results, so:
- enum state: CREATED, PROGRESS, DONE
- result: SUCCESS, FAIL

**Comment by hellais** [comment]
> about state i think in different about each of you. i think to distinguish the temporal state from the results, so:
> enum state: CREATED, PROGRESS, DONE

At least in the desktop app, the transition from state `CREATED` to `PROGRESS` is immediate. Does something relevant happen to transition from `CREATED` to `PROGRESS` in the mobile app?

**Comment by lorenzoPrimi** [comment]
@xanscale I disagree with your first enum as there is no difference between created and progress, they will happen in less than a ms and I don't save the state between these two states. The created or progress state doesn't give us any useful information

**Comment by xanscale** [comment]
they are true. so i prefer @hellais proposal to avoid somthing like

if(state == done || state == uploaded) etcetc

**Comment by lorenzoPrimi** [comment]
Uploaded callbacks is not yet implemented in mk so I don't know what to say about this. @bassosimone 

At the moment the states can be
```
typedef enum
{
    measurementActive,  
    measurementFailed,
    measurementDone,
    measurementUploaded,
    measurementProcessed
} MeasurementState;
```

**Comment by hellais** [comment]
@lorenzoPrimi I would advise against having a state object of that sort, because you can have:

- A measurement that is failed, but also done (done means there is nothing left to do about it except re-run it, yet you would still keep the failed one too perhaps)
- A measurement is not uploaded, but is done
- etc.

I would therefore suggest you keep these inside of separate variables.

Done: is to say you don't have to run the state of this measurement, because it's at it's final state
Failed: is to show you that you failed to run the experiment, but you may still have uploaded it or not
Uploaded: it's just that it's uploaded, whether or not is failed

I am not sure what you mean with processed, but if that is another thing that can happen aside from the rest, it probably should be it's own boolean flag.

**Comment by lorenzoPrimi** [comment]
So I don't understand the concept of done at all. For now done is when the measurement produces an entry (on_entry callback), if that entry is null or invalid the measurement the status is failed.
You can't re run a done, you can re run a failed.

About upload I don't know what to say until I don't see how it will be implemented in mk. I doubt a failed measurement is gonna be uploaded if the json is null.

Processed is a state I copied from your original schema, I guess processed from the pipeline.

**Comment by hellais** [comment]
@lorenzoPrimi I think that if you re-run a test (or measurement), you should either delete the row you are re-running or keep it but somehow mark is as re-run.

I don't think you should attempt to UPDATE an already run measurement, because you may have issues tracking consistency of it (moreover if you are to UDPATE an existing one, you loose track of the fact that you had a failed measurement).

I would therefore suggest having also a flag for `is_rerun` to make a measurement as not re-runnable.

**Comment by lorenzoPrimi** [comment]
@hellais exactly what I do now, delete row and re run the same measurement. I still don't get your point.

**Comment by lorenzoPrimi** [comment]
and you can do it only in the case the measurement is failed. If it's done (a measurement can't be done and failed, done now means positive state) you can't re run it

**Comment by xanscale** [comment]
i think is to define which are the states and what to do for each state. (chat is better)

**Comment by xanscale** [comment]
from the 2 schema there are some aesthetic difference and only 1 pratical difference and is about uploaded

in @lorenzoPrimi scheme uploaded means done.

if we upload only done and not failed so the difference is only aesthetic

**Comment by hellais** [comment]
Based on this discussion I made a PR with the proposed changes in here: https://github.com/ooni/probe-cli/pull/16/files.

I also did a pass at making some of the constraints a bit tighter and setting some reasonable `ON DELETE CASCADE`.

**Comment by hellais** [comment]
This is done.
